// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TodoMVC.module('TodoList.Views', function(Views, App, Backbone, Marionette, $, _) {
  return Views.ItemView = (function(_super) {
    __extends(ItemView, _super);

    function ItemView() {
      return ItemView.__super__.constructor.apply(this, arguments);
    }

    ItemView.prototype.tagName = 'li';

    ItemView.prototype.onEditKeypress = function(e) {
      var ENTER_KEY, ESC_KEY;
      ENTER_KEY = 13;
      ESC_KEY = 27;
      if (e.which === ENTER_KEY) {
        this.onEditFocusout();
      }
      if (e.which === ESC_KEY) {
        this.ui.edit.val(this.model.get('title'));
        return this.$el.removeClass('editing');
      }
    };

    ItemView.prototype.onEditKeypress = function(e) {
      var ENTER_KEY;
      return ENTER_KEY = 13;
    };

    return ItemView;

  })(Marionette.ItemView);
});
